//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.04 at 01:30:36 odp. CET 
//


package net.airtoy.ares.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ares_dotaz_typ.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ares_dotaz_typ">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Standard"/>
 *     &lt;enumeration value="Seznam_Reg"/>
 *     &lt;enumeration value="Vypis_OR"/>
 *     &lt;enumeration value="Vypis_RZP"/>
 *     &lt;enumeration value="Vypis_RES"/>
 *     &lt;enumeration value="Vypis_RZZ"/>
 *     &lt;enumeration value="Basic"/>
 *     &lt;enumeration value="Vypis_DML"/>
 *     &lt;enumeration value="Vypis_CNS"/>
 *     &lt;enumeration value="Vypis_OSS"/>
 *     &lt;enumeration value="Vypis_POZ"/>
 *     &lt;enumeration value="Stdadr"/>
 *     &lt;enumeration value="es"/>
 *     &lt;enumeration value="fo"/>
 *     &lt;enumeration value="ceu"/>
 *     &lt;enumeration value="zm"/>
 *     &lt;enumeration value="szr"/>
 *     &lt;enumeration value="Vypis_OFF"/>
 *     &lt;enumeration value="Vypis_PSH"/>
 *     &lt;enumeration value="Vypis_IR"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ares_dotaz_typ")
@XmlEnum
public enum AresDotazTyp {

    @XmlEnumValue("Standard")
    STANDARD("Standard"),
    @XmlEnumValue("Seznam_Reg")
    SEZNAM_REG("Seznam_Reg"),
    @XmlEnumValue("Vypis_OR")
    VYPIS_OR("Vypis_OR"),
    @XmlEnumValue("Vypis_RZP")
    VYPIS_RZP("Vypis_RZP"),
    @XmlEnumValue("Vypis_RES")
    VYPIS_RES("Vypis_RES"),
    @XmlEnumValue("Vypis_RZZ")
    VYPIS_RZZ("Vypis_RZZ"),
    @XmlEnumValue("Basic")
    BASIC("Basic"),
    @XmlEnumValue("Vypis_DML")
    VYPIS_DML("Vypis_DML"),
    @XmlEnumValue("Vypis_CNS")
    VYPIS_CNS("Vypis_CNS"),
    @XmlEnumValue("Vypis_OSS")
    VYPIS_OSS("Vypis_OSS"),
    @XmlEnumValue("Vypis_POZ")
    VYPIS_POZ("Vypis_POZ"),
    @XmlEnumValue("Stdadr")
    STDADR("Stdadr"),
    @XmlEnumValue("es")
    ES("es"),
    @XmlEnumValue("fo")
    FO("fo"),
    @XmlEnumValue("ceu")
    CEU("ceu"),
    @XmlEnumValue("zm")
    ZM("zm"),
    @XmlEnumValue("szr")
    SZR("szr"),
    @XmlEnumValue("Vypis_OFF")
    VYPIS_OFF("Vypis_OFF"),
    @XmlEnumValue("Vypis_PSH")
    VYPIS_PSH("Vypis_PSH"),
    @XmlEnumValue("Vypis_IR")
    VYPIS_IR("Vypis_IR");
    private final String value;

    AresDotazTyp(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AresDotazTyp fromValue(String v) {
        for (AresDotazTyp c: AresDotazTyp.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
