//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.04 at 01:30:36 odp. CET 
//


package net.airtoy.ares.jaxb;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * údaje o financích v SZR
 * 
 * <p>Java class for fin_szr complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="fin_szr">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Klic" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="Poradi" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="Program_kod" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="16"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Poz_castka" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.5}castka" minOccurs="0"/>
 *         &lt;element name="Priz_castka" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.5}castka" minOccurs="0"/>
 *         &lt;element name="Cerp_castka" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.5}castka" minOccurs="0"/>
 *         &lt;element name="Vrac_castka" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.5}castka" minOccurs="0"/>
 *         &lt;element name="EU_castka" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.5}castka" minOccurs="0"/>
 *         &lt;element name="S_kod" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;maxInclusive value="999"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Rok" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *               &lt;minLength value="4"/>
 *               &lt;pattern value="\d{4}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Utvar" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Reg_cislo" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Cj" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "fin_szr", propOrder = {
    "klic",
    "poradi",
    "programKod",
    "pozCastka",
    "prizCastka",
    "cerpCastka",
    "vracCastka",
    "euCastka",
    "sKod",
    "rok",
    "utvar",
    "regCislo",
    "cj"
})
public class FinSzr {

    @XmlElement(name = "Klic")
    protected Integer klic;
    @XmlElement(name = "Poradi")
    protected Integer poradi;
    @XmlElement(name = "Program_kod")
    protected String programKod;
    @XmlElement(name = "Poz_castka")
    protected BigDecimal pozCastka;
    @XmlElement(name = "Priz_castka")
    protected BigDecimal prizCastka;
    @XmlElement(name = "Cerp_castka")
    protected BigDecimal cerpCastka;
    @XmlElement(name = "Vrac_castka")
    protected BigDecimal vracCastka;
    @XmlElement(name = "EU_castka")
    protected BigDecimal euCastka;
    @XmlElement(name = "S_kod")
    protected Integer sKod;
    @XmlElement(name = "Rok")
    protected String rok;
    @XmlElement(name = "Utvar")
    protected String utvar;
    @XmlElement(name = "Reg_cislo")
    protected String regCislo;
    @XmlElement(name = "Cj")
    protected String cj;

    /**
     * Gets the value of the klic property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getKlic() {
        return klic;
    }

    /**
     * Sets the value of the klic property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setKlic(Integer value) {
        this.klic = value;
    }

    /**
     * Gets the value of the poradi property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPoradi() {
        return poradi;
    }

    /**
     * Sets the value of the poradi property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPoradi(Integer value) {
        this.poradi = value;
    }

    /**
     * Gets the value of the programKod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProgramKod() {
        return programKod;
    }

    /**
     * Sets the value of the programKod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProgramKod(String value) {
        this.programKod = value;
    }

    /**
     * Gets the value of the pozCastka property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPozCastka() {
        return pozCastka;
    }

    /**
     * Sets the value of the pozCastka property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPozCastka(BigDecimal value) {
        this.pozCastka = value;
    }

    /**
     * Gets the value of the prizCastka property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPrizCastka() {
        return prizCastka;
    }

    /**
     * Sets the value of the prizCastka property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPrizCastka(BigDecimal value) {
        this.prizCastka = value;
    }

    /**
     * Gets the value of the cerpCastka property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCerpCastka() {
        return cerpCastka;
    }

    /**
     * Sets the value of the cerpCastka property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCerpCastka(BigDecimal value) {
        this.cerpCastka = value;
    }

    /**
     * Gets the value of the vracCastka property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVracCastka() {
        return vracCastka;
    }

    /**
     * Sets the value of the vracCastka property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVracCastka(BigDecimal value) {
        this.vracCastka = value;
    }

    /**
     * Gets the value of the euCastka property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getEUCastka() {
        return euCastka;
    }

    /**
     * Sets the value of the euCastka property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEUCastka(BigDecimal value) {
        this.euCastka = value;
    }

    /**
     * Gets the value of the sKod property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSKod() {
        return sKod;
    }

    /**
     * Sets the value of the sKod property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSKod(Integer value) {
        this.sKod = value;
    }

    /**
     * Gets the value of the rok property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRok() {
        return rok;
    }

    /**
     * Sets the value of the rok property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRok(String value) {
        this.rok = value;
    }

    /**
     * Gets the value of the utvar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUtvar() {
        return utvar;
    }

    /**
     * Sets the value of the utvar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUtvar(String value) {
        this.utvar = value;
    }

    /**
     * Gets the value of the regCislo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegCislo() {
        return regCislo;
    }

    /**
     * Sets the value of the regCislo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegCislo(String value) {
        this.regCislo = value;
    }

    /**
     * Gets the value of the cj property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCj() {
        return cj;
    }

    /**
     * Sets the value of the cj property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCj(String value) {
        this.cj = value;
    }

}
