//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.04 at 01:30:36 odp. CET 
//


package net.airtoy.ares.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Zástupce a Statutární orgán u právnické osoby navrhuji jako dva již existující elementy.
 * 
 * <p>Java class for osoba_s_adresou complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="osoba_s_adresou">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OsobniUdaje" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.5}osobniUdaje" minOccurs="0"/>
 *         &lt;element name="B" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.5}adresa_ARES" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "osoba_s_adresou", propOrder = {
    "osobniUdaje",
    "b"
})
public class OsobaSAdresou {

    @XmlElement(name = "OsobniUdaje")
    protected OsobniUdaje osobniUdaje;
    @XmlElement(name = "B")
    protected AdresaARES b;

    /**
     * Gets the value of the osobniUdaje property.
     * 
     * @return
     *     possible object is
     *     {@link OsobniUdaje }
     *     
     */
    public OsobniUdaje getOsobniUdaje() {
        return osobniUdaje;
    }

    /**
     * Sets the value of the osobniUdaje property.
     * 
     * @param value
     *     allowed object is
     *     {@link OsobniUdaje }
     *     
     */
    public void setOsobniUdaje(OsobniUdaje value) {
        this.osobniUdaje = value;
    }

    /**
     * Gets the value of the b property.
     * 
     * @return
     *     possible object is
     *     {@link AdresaARES }
     *     
     */
    public AdresaARES getB() {
        return b;
    }

    /**
     * Sets the value of the b property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdresaARES }
     *     
     */
    public void setB(AdresaARES value) {
        this.b = value;
    }

}
