//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.04 at 01:30:36 odp. CET 
//


package net.airtoy.ares.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * údaje o fyzické osobě v EZP
 * 
 * <p>Java class for osoba_ezp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="osoba_ezp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Osoba_szr" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.5}osoba_szr"/>
 *         &lt;element name="Angazma_szr" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.5}angazma_szr"/>
 *         &lt;element name="AE" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.5}adresa_ezp"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "osoba_ezp", propOrder = {
    "osobaSzr",
    "angazmaSzr",
    "ae"
})
public class OsobaEzp {

    @XmlElement(name = "Osoba_szr", required = true)
    protected OsobaSzr osobaSzr;
    @XmlElement(name = "Angazma_szr", required = true)
    protected AngazmaSzr angazmaSzr;
    @XmlElement(name = "AE", required = true)
    protected AdresaEzp ae;

    /**
     * Gets the value of the osobaSzr property.
     * 
     * @return
     *     possible object is
     *     {@link OsobaSzr }
     *     
     */
    public OsobaSzr getOsobaSzr() {
        return osobaSzr;
    }

    /**
     * Sets the value of the osobaSzr property.
     * 
     * @param value
     *     allowed object is
     *     {@link OsobaSzr }
     *     
     */
    public void setOsobaSzr(OsobaSzr value) {
        this.osobaSzr = value;
    }

    /**
     * Gets the value of the angazmaSzr property.
     * 
     * @return
     *     possible object is
     *     {@link AngazmaSzr }
     *     
     */
    public AngazmaSzr getAngazmaSzr() {
        return angazmaSzr;
    }

    /**
     * Sets the value of the angazmaSzr property.
     * 
     * @param value
     *     allowed object is
     *     {@link AngazmaSzr }
     *     
     */
    public void setAngazmaSzr(AngazmaSzr value) {
        this.angazmaSzr = value;
    }

    /**
     * Gets the value of the ae property.
     * 
     * @return
     *     possible object is
     *     {@link AdresaEzp }
     *     
     */
    public AdresaEzp getAE() {
        return ae;
    }

    /**
     * Sets the value of the ae property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdresaEzp }
     *     
     */
    public void setAE(AdresaEzp value) {
        this.ae = value;
    }

}
