//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.04 at 01:30:36 odp. CET 
//


package net.airtoy.ares.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * popis jedné pokuty
 * 
 * <p>Java class for pokuta complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="pokuta">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DatumUlozeni" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="Vyse" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Popis" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Poznamka" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "pokuta", propOrder = {
    "datumUlozeni",
    "vyse",
    "popis",
    "poznamka"
})
public class Pokuta {

    @XmlElement(name = "DatumUlozeni", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumUlozeni;
    @XmlElement(name = "Vyse", required = true)
    protected String vyse;
    @XmlElement(name = "Popis", required = true)
    protected String popis;
    @XmlElement(name = "Poznamka", required = true)
    protected String poznamka;

    /**
     * Gets the value of the datumUlozeni property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumUlozeni() {
        return datumUlozeni;
    }

    /**
     * Sets the value of the datumUlozeni property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumUlozeni(XMLGregorianCalendar value) {
        this.datumUlozeni = value;
    }

    /**
     * Gets the value of the vyse property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVyse() {
        return vyse;
    }

    /**
     * Sets the value of the vyse property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVyse(String value) {
        this.vyse = value;
    }

    /**
     * Gets the value of the popis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPopis() {
        return popis;
    }

    /**
     * Sets the value of the popis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPopis(String value) {
        this.popis = value;
    }

    /**
     * Gets the value of the poznamka property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPoznamka() {
        return poznamka;
    }

    /**
     * Sets the value of the poznamka property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPoznamka(String value) {
        this.poznamka = value;
    }

}
