//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.04 at 01:30:36 odp. CET 
//


package net.airtoy.ares.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Údaje o provozovnách subjektu
 * 
 * <p>Java class for provozovna complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="provozovna">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Zahajeni" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="Ukonceni" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="Typ_provozovny" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.5}typ_provozovny" minOccurs="0"/>
 *         &lt;element name="NPR" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.5}nazev_provozovny" minOccurs="0"/>
 *         &lt;element name="AP" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.5}adresa_ARES"/>
 *         &lt;element name="Obory_cinnosti" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.5}obory_cinnosti" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "provozovna", propOrder = {
    "zahajeni",
    "ukonceni",
    "typProvozovny",
    "npr",
    "ap",
    "oboryCinnosti"
})
public class Provozovna {

    @XmlElement(name = "Zahajeni")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar zahajeni;
    @XmlElement(name = "Ukonceni")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar ukonceni;
    @XmlElement(name = "Typ_provozovny")
    protected String typProvozovny;
    @XmlElement(name = "NPR")
    protected String npr;
    @XmlElement(name = "AP", required = true)
    protected AdresaARES ap;
    @XmlElement(name = "Obory_cinnosti")
    protected OboryCinnosti oboryCinnosti;

    /**
     * Gets the value of the zahajeni property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getZahajeni() {
        return zahajeni;
    }

    /**
     * Sets the value of the zahajeni property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setZahajeni(XMLGregorianCalendar value) {
        this.zahajeni = value;
    }

    /**
     * Gets the value of the ukonceni property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getUkonceni() {
        return ukonceni;
    }

    /**
     * Sets the value of the ukonceni property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setUkonceni(XMLGregorianCalendar value) {
        this.ukonceni = value;
    }

    /**
     * Gets the value of the typProvozovny property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypProvozovny() {
        return typProvozovny;
    }

    /**
     * Sets the value of the typProvozovny property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypProvozovny(String value) {
        this.typProvozovny = value;
    }

    /**
     * Gets the value of the npr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNPR() {
        return npr;
    }

    /**
     * Sets the value of the npr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNPR(String value) {
        this.npr = value;
    }

    /**
     * Gets the value of the ap property.
     * 
     * @return
     *     possible object is
     *     {@link AdresaARES }
     *     
     */
    public AdresaARES getAP() {
        return ap;
    }

    /**
     * Sets the value of the ap property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdresaARES }
     *     
     */
    public void setAP(AdresaARES value) {
        this.ap = value;
    }

    /**
     * Gets the value of the oboryCinnosti property.
     * 
     * @return
     *     possible object is
     *     {@link OboryCinnosti }
     *     
     */
    public OboryCinnosti getOboryCinnosti() {
        return oboryCinnosti;
    }

    /**
     * Sets the value of the oboryCinnosti property.
     * 
     * @param value
     *     allowed object is
     *     {@link OboryCinnosti }
     *     
     */
    public void setOboryCinnosti(OboryCinnosti value) {
        this.oboryCinnosti = value;
    }

}
