//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.04 at 01:30:36 odp. CET 
//


package net.airtoy.ares.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * registrace subjektu u pojišťoven
 * 
 * <p>Java class for registracePojistovna complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="registracePojistovna">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PojistovnaId" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PojistovnaIco" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/uvis_datatypes/v_1.0.3}ico" minOccurs="0"/>
 *         &lt;element name="PojistovnaNazev" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "registracePojistovna", propOrder = {
    "pojistovnaId",
    "pojistovnaIco",
    "pojistovnaNazev"
})
public class RegistracePojistovna {

    @XmlElement(name = "PojistovnaId", type = Integer.class)
    protected List<Integer> pojistovnaId;
    @XmlElement(name = "PojistovnaIco")
    protected String pojistovnaIco;
    @XmlElement(name = "PojistovnaNazev")
    protected String pojistovnaNazev;

    /**
     * Gets the value of the pojistovnaId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pojistovnaId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPojistovnaId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Integer }
     * 
     * 
     */
    public List<Integer> getPojistovnaId() {
        if (pojistovnaId == null) {
            pojistovnaId = new ArrayList<Integer>();
        }
        return this.pojistovnaId;
    }

    /**
     * Gets the value of the pojistovnaIco property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPojistovnaIco() {
        return pojistovnaIco;
    }

    /**
     * Sets the value of the pojistovnaIco property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPojistovnaIco(String value) {
        this.pojistovnaIco = value;
    }

    /**
     * Gets the value of the pojistovnaNazev property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPojistovnaNazev() {
        return pojistovnaNazev;
    }

    /**
     * Sets the value of the pojistovnaNazev property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPojistovnaNazev(String value) {
        this.pojistovnaNazev = value;
    }

}
