//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.04 at 01:30:36 odp. CET 
//


package net.airtoy.ares.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * registrace v ISPOZ (tabulka registrace + dvě položky z typu osoby v xml, ale bez MinuleREG)
 * 
 * <p>Java class for registraceISPOZ complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="registraceISPOZ">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Datum_zmeny" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="RegistracniCislo" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.5}registracnicislo" minOccurs="0"/>
 *         &lt;element name="Subregistr" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TypOsoby" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DatumZapisu" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="DomovskaPrislusnost" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Typstavu" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Datumstavu" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "registraceISPOZ", propOrder = {
    "datumZmeny",
    "registracniCislo",
    "subregistr",
    "typOsoby",
    "datumZapisu",
    "domovskaPrislusnost",
    "typstavu",
    "datumstavu"
})
public class RegistraceISPOZ {

    @XmlElement(name = "Datum_zmeny")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumZmeny;
    @XmlElement(name = "RegistracniCislo")
    protected String registracniCislo;
    @XmlElement(name = "Subregistr", required = true)
    protected String subregistr;
    @XmlElement(name = "TypOsoby", required = true)
    protected String typOsoby;
    @XmlElement(name = "DatumZapisu", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumZapisu;
    @XmlElement(name = "DomovskaPrislusnost")
    protected String domovskaPrislusnost;
    @XmlElement(name = "Typstavu", required = true)
    protected String typstavu;
    @XmlElement(name = "Datumstavu", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumstavu;

    /**
     * Gets the value of the datumZmeny property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumZmeny() {
        return datumZmeny;
    }

    /**
     * Sets the value of the datumZmeny property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumZmeny(XMLGregorianCalendar value) {
        this.datumZmeny = value;
    }

    /**
     * Gets the value of the registracniCislo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegistracniCislo() {
        return registracniCislo;
    }

    /**
     * Sets the value of the registracniCislo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegistracniCislo(String value) {
        this.registracniCislo = value;
    }

    /**
     * Gets the value of the subregistr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubregistr() {
        return subregistr;
    }

    /**
     * Sets the value of the subregistr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubregistr(String value) {
        this.subregistr = value;
    }

    /**
     * Gets the value of the typOsoby property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypOsoby() {
        return typOsoby;
    }

    /**
     * Sets the value of the typOsoby property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypOsoby(String value) {
        this.typOsoby = value;
    }

    /**
     * Gets the value of the datumZapisu property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumZapisu() {
        return datumZapisu;
    }

    /**
     * Sets the value of the datumZapisu property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumZapisu(XMLGregorianCalendar value) {
        this.datumZapisu = value;
    }

    /**
     * Gets the value of the domovskaPrislusnost property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDomovskaPrislusnost() {
        return domovskaPrislusnost;
    }

    /**
     * Sets the value of the domovskaPrislusnost property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDomovskaPrislusnost(String value) {
        this.domovskaPrislusnost = value;
    }

    /**
     * Gets the value of the typstavu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypstavu() {
        return typstavu;
    }

    /**
     * Sets the value of the typstavu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypstavu(String value) {
        this.typstavu = value;
    }

    /**
     * Gets the value of the datumstavu property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumstavu() {
        return datumstavu;
    }

    /**
     * Sets the value of the datumstavu property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumstavu(XMLGregorianCalendar value) {
        this.datumstavu = value;
    }

}
