//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.04 at 01:30:36 odp. CET 
//


package net.airtoy.ares.jaxb;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for statisticke_udaje complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="statisticke_udaje">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ISK" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="ISE" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.5}institucionarni_sektor" minOccurs="0"/>
 *         &lt;element name="KPP" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.5}kategorie_poctu_pracovniku" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "statisticke_udaje", propOrder = {
    "isk",
    "ise",
    "kpp"
})
public class StatistickeUdaje {

    @XmlElement(name = "ISK")
    protected BigInteger isk;
    @XmlElement(name = "ISE")
    protected InstitucionarniSektor ise;
    @XmlElement(name = "KPP")
    protected KategoriePoctuPracovniku kpp;

    /**
     * Gets the value of the isk property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getISK() {
        return isk;
    }

    /**
     * Sets the value of the isk property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setISK(BigInteger value) {
        this.isk = value;
    }

    /**
     * Gets the value of the ise property.
     * 
     * @return
     *     possible object is
     *     {@link InstitucionarniSektor }
     *     
     */
    public InstitucionarniSektor getISE() {
        return ise;
    }

    /**
     * Sets the value of the ise property.
     * 
     * @param value
     *     allowed object is
     *     {@link InstitucionarniSektor }
     *     
     */
    public void setISE(InstitucionarniSektor value) {
        this.ise = value;
    }

    /**
     * Gets the value of the kpp property.
     * 
     * @return
     *     possible object is
     *     {@link KategoriePoctuPracovniku }
     *     
     */
    public KategoriePoctuPracovniku getKPP() {
        return kpp;
    }

    /**
     * Sets the value of the kpp property.
     * 
     * @param value
     *     allowed object is
     *     {@link KategoriePoctuPracovniku }
     *     
     */
    public void setKPP(KategoriePoctuPracovniku value) {
        this.kpp = value;
    }

}
