//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.04 at 01:30:36 odp. CET 
//


package net.airtoy.ares.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * S subjektu: Aktivní / Zaniklý a atributy KKZ, VY, ZAM, LI
 * 
 * <p>Java class for stav complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="stav">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SSU" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.5}stav_subjektu" minOccurs="0"/>
 *         &lt;element name="KKZ" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.5}stav_KVZ"/>
 *         &lt;element name="VY" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.5}stav_KVZ"/>
 *         &lt;element name="ZAM" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.5}stav_KVZ"/>
 *         &lt;element name="LI" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.5}stav_KVZ"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "stav", propOrder = {
    "ssu",
    "kkz",
    "vy",
    "zam",
    "li"
})
public class Stav {

    @XmlElement(name = "SSU")
    protected StavSubjektu ssu;
    @XmlElement(name = "KKZ", required = true)
    protected StavKVZ kkz;
    @XmlElement(name = "VY", required = true)
    protected StavKVZ vy;
    @XmlElement(name = "ZAM", required = true)
    protected StavKVZ zam;
    @XmlElement(name = "LI", required = true)
    protected StavKVZ li;

    /**
     * Gets the value of the ssu property.
     * 
     * @return
     *     possible object is
     *     {@link StavSubjektu }
     *     
     */
    public StavSubjektu getSSU() {
        return ssu;
    }

    /**
     * Sets the value of the ssu property.
     * 
     * @param value
     *     allowed object is
     *     {@link StavSubjektu }
     *     
     */
    public void setSSU(StavSubjektu value) {
        this.ssu = value;
    }

    /**
     * Gets the value of the kkz property.
     * 
     * @return
     *     possible object is
     *     {@link StavKVZ }
     *     
     */
    public StavKVZ getKKZ() {
        return kkz;
    }

    /**
     * Sets the value of the kkz property.
     * 
     * @param value
     *     allowed object is
     *     {@link StavKVZ }
     *     
     */
    public void setKKZ(StavKVZ value) {
        this.kkz = value;
    }

    /**
     * Gets the value of the vy property.
     * 
     * @return
     *     possible object is
     *     {@link StavKVZ }
     *     
     */
    public StavKVZ getVY() {
        return vy;
    }

    /**
     * Sets the value of the vy property.
     * 
     * @param value
     *     allowed object is
     *     {@link StavKVZ }
     *     
     */
    public void setVY(StavKVZ value) {
        this.vy = value;
    }

    /**
     * Gets the value of the zam property.
     * 
     * @return
     *     possible object is
     *     {@link StavKVZ }
     *     
     */
    public StavKVZ getZAM() {
        return zam;
    }

    /**
     * Sets the value of the zam property.
     * 
     * @param value
     *     allowed object is
     *     {@link StavKVZ }
     *     
     */
    public void setZAM(StavKVZ value) {
        this.zam = value;
    }

    /**
     * Gets the value of the li property.
     * 
     * @return
     *     possible object is
     *     {@link StavKVZ }
     *     
     */
    public StavKVZ getLI() {
        return li;
    }

    /**
     * Sets the value of the li property.
     * 
     * @param value
     *     allowed object is
     *     {@link StavKVZ }
     *     
     */
    public void setLI(StavKVZ value) {
        this.li = value;
    }

}
