//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.04 at 01:30:36 odp. CET 
//


package net.airtoy.ares.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * fyzická nebo právnická osoba
 * 
 * <p>Java class for subjekt_ISPOZ complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="subjekt_ISPOZ">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="UVOD" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.5}uvod" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element name="PravnickaOsoba" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.5}pravnickaOsobaISPOZ"/>
 *           &lt;element name="FyzickaOsoba" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.5}fyzickaOsobaISPOZ"/>
 *           &lt;element name="SeznamOsob" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.5}seznamosob"/>
 *         &lt;/choice>
 *         &lt;element name="StejneIc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Podrizeni" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "subjekt_ISPOZ", propOrder = {
    "uvod",
    "pravnickaOsoba",
    "fyzickaOsoba",
    "seznamOsob",
    "stejneIc",
    "podrizeni"
})
public class SubjektISPOZ {

    @XmlElement(name = "UVOD")
    protected Uvod uvod;
    @XmlElement(name = "PravnickaOsoba")
    protected PravnickaOsobaISPOZ pravnickaOsoba;
    @XmlElement(name = "FyzickaOsoba")
    protected FyzickaOsobaISPOZ fyzickaOsoba;
    @XmlElement(name = "SeznamOsob")
    protected Seznamosob seznamOsob;
    @XmlElement(name = "StejneIc")
    protected String stejneIc;
    @XmlElement(name = "Podrizeni")
    protected String podrizeni;

    /**
     * Gets the value of the uvod property.
     * 
     * @return
     *     possible object is
     *     {@link Uvod }
     *     
     */
    public Uvod getUVOD() {
        return uvod;
    }

    /**
     * Sets the value of the uvod property.
     * 
     * @param value
     *     allowed object is
     *     {@link Uvod }
     *     
     */
    public void setUVOD(Uvod value) {
        this.uvod = value;
    }

    /**
     * Gets the value of the pravnickaOsoba property.
     * 
     * @return
     *     possible object is
     *     {@link PravnickaOsobaISPOZ }
     *     
     */
    public PravnickaOsobaISPOZ getPravnickaOsoba() {
        return pravnickaOsoba;
    }

    /**
     * Sets the value of the pravnickaOsoba property.
     * 
     * @param value
     *     allowed object is
     *     {@link PravnickaOsobaISPOZ }
     *     
     */
    public void setPravnickaOsoba(PravnickaOsobaISPOZ value) {
        this.pravnickaOsoba = value;
    }

    /**
     * Gets the value of the fyzickaOsoba property.
     * 
     * @return
     *     possible object is
     *     {@link FyzickaOsobaISPOZ }
     *     
     */
    public FyzickaOsobaISPOZ getFyzickaOsoba() {
        return fyzickaOsoba;
    }

    /**
     * Sets the value of the fyzickaOsoba property.
     * 
     * @param value
     *     allowed object is
     *     {@link FyzickaOsobaISPOZ }
     *     
     */
    public void setFyzickaOsoba(FyzickaOsobaISPOZ value) {
        this.fyzickaOsoba = value;
    }

    /**
     * Gets the value of the seznamOsob property.
     * 
     * @return
     *     possible object is
     *     {@link Seznamosob }
     *     
     */
    public Seznamosob getSeznamOsob() {
        return seznamOsob;
    }

    /**
     * Sets the value of the seznamOsob property.
     * 
     * @param value
     *     allowed object is
     *     {@link Seznamosob }
     *     
     */
    public void setSeznamOsob(Seznamosob value) {
        this.seznamOsob = value;
    }

    /**
     * Gets the value of the stejneIc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStejneIc() {
        return stejneIc;
    }

    /**
     * Sets the value of the stejneIc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStejneIc(String value) {
        this.stejneIc = value;
    }

    /**
     * Gets the value of the podrizeni property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPodrizeni() {
        return podrizeni;
    }

    /**
     * Sets the value of the podrizeni property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPodrizeni(String value) {
        this.podrizeni = value;
    }

}
