//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.04 at 01:30:36 odp. CET 
//


package net.airtoy.ares.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for vypis_ceu_detail complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="vypis_ceu_detail">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IC" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/uvis_datatypes/v_1.0.3}ico" minOccurs="0"/>
 *         &lt;element name="OF" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/uvis_datatypes/v_1.0.3}obchodni_firma" minOccurs="0"/>
 *         &lt;element name="PF" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.5}pravni_forma" minOccurs="0"/>
 *         &lt;element name="obec" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/uvis_datatypes/v_1.0.3}nazev_obce" minOccurs="0"/>
 *         &lt;element name="psc" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/uvis_datatypes/v_1.0.3}psc" minOccurs="0"/>
 *         &lt;element name="uvp" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/uvis_datatypes/v_1.0.3}nazev_ulice" minOccurs="0"/>
 *         &lt;element name="obec_b" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/uvis_datatypes/v_1.0.3}nazev_obce" minOccurs="0"/>
 *         &lt;element name="psc_b" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/uvis_datatypes/v_1.0.3}psc" minOccurs="0"/>
 *         &lt;element name="uvp_b" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/uvis_datatypes/v_1.0.3}nazev_ulice" minOccurs="0"/>
 *         &lt;element name="S_k" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.5}stav_upadce_CEU" minOccurs="0"/>
 *         &lt;element name="S_v" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.5}stav_upadce_CEU" minOccurs="0"/>
 *         &lt;element name="ukony" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.5}jednotlive_ukony" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "vypis_ceu_detail", propOrder = {
    "ic",
    "of",
    "pf",
    "obec",
    "psc",
    "uvp",
    "obecB",
    "pscB",
    "uvpB",
    "sk",
    "sv",
    "ukony"
})
public class VypisCeuDetail {

    @XmlElement(name = "IC")
    protected String ic;
    @XmlElement(name = "OF")
    protected String of;
    @XmlElement(name = "PF")
    protected PravniForma pf;
    protected String obec;
    protected String psc;
    protected String uvp;
    @XmlElement(name = "obec_b")
    protected String obecB;
    @XmlElement(name = "psc_b")
    protected String pscB;
    @XmlElement(name = "uvp_b")
    protected String uvpB;
    @XmlElement(name = "S_k")
    protected StavUpadceCEU sk;
    @XmlElement(name = "S_v")
    protected StavUpadceCEU sv;
    protected List<JednotliveUkony> ukony;

    /**
     * Gets the value of the ic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIC() {
        return ic;
    }

    /**
     * Sets the value of the ic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIC(String value) {
        this.ic = value;
    }

    /**
     * Gets the value of the of property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOF() {
        return of;
    }

    /**
     * Sets the value of the of property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOF(String value) {
        this.of = value;
    }

    /**
     * Gets the value of the pf property.
     * 
     * @return
     *     possible object is
     *     {@link PravniForma }
     *     
     */
    public PravniForma getPF() {
        return pf;
    }

    /**
     * Sets the value of the pf property.
     * 
     * @param value
     *     allowed object is
     *     {@link PravniForma }
     *     
     */
    public void setPF(PravniForma value) {
        this.pf = value;
    }

    /**
     * Gets the value of the obec property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObec() {
        return obec;
    }

    /**
     * Sets the value of the obec property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObec(String value) {
        this.obec = value;
    }

    /**
     * Gets the value of the psc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPsc() {
        return psc;
    }

    /**
     * Sets the value of the psc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPsc(String value) {
        this.psc = value;
    }

    /**
     * Gets the value of the uvp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUvp() {
        return uvp;
    }

    /**
     * Sets the value of the uvp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUvp(String value) {
        this.uvp = value;
    }

    /**
     * Gets the value of the obecB property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObecB() {
        return obecB;
    }

    /**
     * Sets the value of the obecB property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObecB(String value) {
        this.obecB = value;
    }

    /**
     * Gets the value of the pscB property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPscB() {
        return pscB;
    }

    /**
     * Sets the value of the pscB property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPscB(String value) {
        this.pscB = value;
    }

    /**
     * Gets the value of the uvpB property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUvpB() {
        return uvpB;
    }

    /**
     * Sets the value of the uvpB property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUvpB(String value) {
        this.uvpB = value;
    }

    /**
     * Gets the value of the sk property.
     * 
     * @return
     *     possible object is
     *     {@link StavUpadceCEU }
     *     
     */
    public StavUpadceCEU getSK() {
        return sk;
    }

    /**
     * Sets the value of the sk property.
     * 
     * @param value
     *     allowed object is
     *     {@link StavUpadceCEU }
     *     
     */
    public void setSK(StavUpadceCEU value) {
        this.sk = value;
    }

    /**
     * Gets the value of the sv property.
     * 
     * @return
     *     possible object is
     *     {@link StavUpadceCEU }
     *     
     */
    public StavUpadceCEU getSV() {
        return sv;
    }

    /**
     * Sets the value of the sv property.
     * 
     * @param value
     *     allowed object is
     *     {@link StavUpadceCEU }
     *     
     */
    public void setSV(StavUpadceCEU value) {
        this.sv = value;
    }

    /**
     * Gets the value of the ukony property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ukony property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUkony().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JednotliveUkony }
     * 
     * 
     */
    public List<JednotliveUkony> getUkony() {
        if (ukony == null) {
            ukony = new ArrayList<JednotliveUkony>();
        }
        return this.ukony;
    }

}
