//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.04 at 01:30:36 odp. CET 
//


package net.airtoy.ares.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * zprostředkovatel
 * 
 * <p>Java class for zprostredkovatel complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="zprostredkovatel">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="JP" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OF" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RegistracniCislo" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.5}registracnicislo" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "zprostredkovatel", propOrder = {
    "jp",
    "of",
    "registracniCislo"
})
public class Zprostredkovatel {

    @XmlElement(name = "JP")
    protected String jp;
    @XmlElement(name = "OF")
    protected String of;
    @XmlElement(name = "RegistracniCislo")
    protected String registracniCislo;

    /**
     * Gets the value of the jp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJP() {
        return jp;
    }

    /**
     * Sets the value of the jp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJP(String value) {
        this.jp = value;
    }

    /**
     * Gets the value of the of property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOF() {
        return of;
    }

    /**
     * Sets the value of the of property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOF(String value) {
        this.of = value;
    }

    /**
     * Gets the value of the registracniCislo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegistracniCislo() {
        return registracniCislo;
    }

    /**
     * Sets the value of the registracniCislo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegistracniCislo(String value) {
        this.registracniCislo = value;
    }

}
