//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.04 at 01:30:36 odp. CET 
//


package net.airtoy.ares.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * zprostředkovatelé
 * 
 * <p>Java class for zprostredkovatele complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="zprostredkovatele">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Zprostredkovatel" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.5}zprostredkovatel" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "zprostredkovatele", propOrder = {
    "zprostredkovatel"
})
public class Zprostredkovatele {

    @XmlElement(name = "Zprostredkovatel", required = true)
    protected List<Zprostredkovatel> zprostredkovatel;

    /**
     * Gets the value of the zprostredkovatel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the zprostredkovatel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getZprostredkovatel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Zprostredkovatel }
     * 
     * 
     */
    public List<Zprostredkovatel> getZprostredkovatel() {
        if (zprostredkovatel == null) {
            zprostredkovatel = new ArrayList<Zprostredkovatel>();
        }
        return this.zprostredkovatel;
    }

}
